lex = {
    "t": ["regnet"],
    "e": [
        "Bill",
        "Andrew",
        "Mathis",
        "Mark",
        "Peter",
        "Markus",
        "Klaus",
        "Twilight",
        "Rome",
        "Nimmerland",
        "Maria",
    ],
    "<t, t>": ["not"],
    "": ["is", "ist", "of", "es", "ein", "auf", "wo", "-s"],
    "pron": ["er", "he", "his", "she"],
    "<e, t>": [
        "mad",
        "person",
        "essen",
        "sleeps",
        "tanzt",
        "schnarcht",
        "verschüchterte",
        "große",
        "schnarchende",
        "arbeitet",
        "Hunde",
        "Türen",
        "snore",
        "schuldiger",
        "Mann",
        "Männer",
        "kleinen",
        "Fee",
        "fliegt",
        "Jungen",
        "Schüler",
        "Buch",
        "Junge",
        "Wolf",
        "Blumen",
        "flowers",
        "Idiot",
        "cat",
        "sad",
        "fliegender",
        "fliegende",
    ],
    "<e, <e, t>>": [
        "hits",
        "invite",
        "beobachtet",
        "belästigt",
        "bought",
        "ate",
        "hated",
        "zwicken",
        "schließen",
        "destruction",
        "malt",
        "aus",
        "stolz",
    ],
    "<e, <e, e>>": ["und_{ind}"],
    "<e, <e, <e, t>>>": ["gibt"],
    "<t, <t, t>>": ["und", "oder", "or"],
    "<<e, t>, <<e, t>, t>>": ["all", "alle", "einige", "some", "a"],
    "<<e, t>, t>": ["nobody"],
    "<<e, t>, e>": ["the", "den", "der", "die", "das", "dem"],
    "index": ["1", "2", "der_{RP}"],
    "trace": ["$t$", "t"],
}
